Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "timtimTurt.py", line 55, in <module>
    moveHare(hare)
NameError: name 'moveHare' is not defined
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
